version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '02:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'prabhuignoto'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      development-dependencies:
        dependency-type: 'development'
        patterns:
          - '@types/*'
          - '@typescript-eslint/*'
          - 'eslint*'
          - 'prettier'
          - 'stylelint*'
          - '@rollup/*'
          - 'rollup*'
          - 'vite'
          - '@vitejs/*'
      vue-ecosystem:
        patterns:
          - 'vue*'
          - '@vue/*'
    ignore:
      - dependency-name: 'vue'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'ci'
