name: Cross-Platform Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6 AM


jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: ['22']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: ${{ matrix.node-version }}
          pnpm-version: 9.0.0

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ matrix.node-version }}-
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Build library
        run: pnpm build

      - name: Build demo
        run: pnpm build

      - name: Verify build outputs
        shell: bash
        run: |
          if [ ! -f "dist/vue-float-menu.js" ]; then
            echo "Main build file not found"
            exit 1
          fi
          if [ ! -d "dist" ] || [ ! "$(ls -A dist)" ]; then
            echo "Dist directory is empty"
            exit 1
          fi
          echo "Build verification passed"
